---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-kubernetes-basica-00
spec:
  selector:
    matchLabels:
      app: hola-kubernetes-basica-00
  replicas: 3 # numero de pods
  strategy:
  type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hola-kubernetes-basica-00
    spec:
      containers:
      - name: hola-kubernetes-basica-00
        image: marisamartinserrano/hola-kubernetes-basica:0.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "2m"
          limits:
            memory: "128Mi"
            cpu: "2m"