apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hola-kubernetes-basica-00
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hola-kubernetes-basica-00
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1